import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
let csrf='',displayTimezone='UTC';
async function api(url,method='GET',body){const r=await fetch('/api'+url,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},...(body===undefined?{}:{body:JSON.stringify(body)})});let data;try{data=await r.json();}catch{throw new Error('The server is unavailable. Please retry.');}if(!r.ok){if(r.status===401&&url!=='/login')window.dispatchEvent(new Event('session-expired'));throw new Error(data.error||'Request failed');}return data;}
const brands={ghl:'GoHighLevel',tintwiz:'TintWiz',qbo:'QuickBooks',hyros:'Hyros'};
const count=v=>v==null?'—':new Intl.NumberFormat().format(v),pct=v=>v==null?'—':`${Math.round(v*100)}%`,fixed=v=>v==null?'—':new Intl.NumberFormat('en',{maximumFractionDigits:1}).format(v);
const date=v=>v?new Date(v).toLocaleString('en',{timeZone:displayTimezone}): 'Not supplied';
function Icon({name}){return <span className="icon" aria-hidden="true">{({Overview:'◫',Team:'♙',Connections:'⇄',Activity:'≡',People:'◎'})[name]||'↗'}</span>;}
function FormField({label,...props}){return <label>{label}<input {...props}/></label>;}
function App(){
 const [user,setUser]=useState(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState('Overview'),[data,setData]=useState(null),[range,setRange]=useState(null),[dates,setDates]=useState(null),[revision,setRevision]=useState(0);
 useEffect(()=>{const expired=()=>{setUser(null);setData(null);setError('Your session ended. Please sign in again.');};window.addEventListener('session-expired',expired);api('/me').then(u=>{csrf=u.csrf;setUser(u);}).catch(()=>setError('')).finally(()=>setReady(true));return()=>window.removeEventListener('session-expired',expired);},[]);
 useEffect(()=>{if(user){const end=new Intl.DateTimeFormat('en-CA',{timeZone:user.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),r={start:end.slice(0,8)+'01',end};setRange(r);setDates(r);setPage('Overview');}},[user?.id]);
 useEffect(()=>{if(!user||!range)return;let active=true;setData(null);api('/dashboard?'+new URLSearchParams(range)).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[user,range,revision]);
 async function act(fn,message=''){setError('');setNotice('');setBusy(true);try{await fn();if(message)setNotice(message);setRevision(x=>x+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(user)displayTimezone=user.timezone;
 const money=v=>v==null?'—':new Intl.NumberFormat('en',{style:'currency',currency:user?.currency||'USD',minimumFractionDigits:0,maximumFractionDigits:2}).format(v/100);
 if(!ready)return <div className="boot">Loading Bayline…</div>;
 if(!user)return <main className="login"><section className="login-story"><div className="wordmark"><b className="logo">B</b> BAYLINE<span>GROWTH</span></div><div><p className="eyebrow">THE BUSINESS BEHIND THE FINISH</p><h1>A clearer view.<br/>A stronger shop.</h1><p>Leads, service performance and business results.<br/>One place to see what needs your attention.</p><div className="story-lines"><i/><i/><i/><i/><i/></div></div><small>TINT · CERAMIC · PPF · WRAP</small></section><section className="login-panel"><p className="eyebrow">WELCOME BACK</p><h2>Sign in to your workspace</h2><p className="muted">Use the account provided by your business owner.</p>{error&&<p role="alert" className="error">{error}</p>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(async()=>{await api('/login','POST',Object.fromEntries(f));const u=await api('/me');csrf=u.csrf;setUser(u);});}}><FormField label="Email address" name="email" type="email" autoComplete="username" required/><FormField label="Password" name="password" type="password" autoComplete="current-password" required maxLength={128}/><button disabled={busy} className="primary">{busy?'Signing in…':'Sign in →'}</button></form><small className="muted">Need access or a password reset? Contact your administrator.</small></section></main>;
 const nav=['Overview',...(user.role!=='team'?['Team']:[]),...(user.role==='owner'?['Connections','Activity','People']:[])];
 return <div className="shell"><aside className="sidebar"><a className="wordmark" href="/" aria-label="Bayline home"><b className="logo">B</b><div>BAYLINE<span>GROWTH</span></div></a><p className="nav-caption">WORKSPACE</p><nav aria-label="Main navigation">{nav.map(n=><button key={n} className={page===n?'selected':''} aria-current={page===n?'page':undefined} onClick={()=>{setPage(n);setError('');setNotice('');}}><Icon name={n}/>{n}</button>)}</nav><div className="sidebar-bottom"><span className="status-dot"/>Business workspace<p>Clarity for every bay.</p><div className="profile"><span className="avatar">{user.name[0]}</span><div><b>{user.name}</b><small>{user.role}</small></div></div><button className="signout" onClick={()=>act(async()=>{await api('/logout','POST',{});setUser(null);setData(null);})}>Sign out ↗</button></div></aside><main className="workspace"><header className="topbar"><span>Workspace <span className="slash">/</span> {page}</span><span className="timezone">{user.timezone} <span className="pill">{user.role}</span></span></header><div className="content"><div className="page-heading"><div><p className="eyebrow">{user.role==='team'?'YOUR ASSIGNED WORK':'YOUR BUSINESS, IN FOCUS'}</p><h1>{page==='Overview'?'Performance overview':page==='Team'?'Team performance':page==='Connections'?'Data & connections':page==='People'?'People & access':'Activity log'}</h1><p className="muted">{page==='Overview'?'Know where you stand. See where to focus next.':page==='Connections'?'Review complete snapshots before they enter your dashboard.':page==='Team'?'Consistent measures. Clear responsibility.':page==='People'?'Set roles and map each person to their source accounts.':'A record of changes made in this workspace.'}</p></div>{dates&&<form className="date-range" onSubmit={e=>{e.preventDefault();setRange({...dates});}}><FormField label="From" type="date" required value={dates.start} onChange={e=>setDates({...dates,start:e.target.value})}/><FormField label="Through" type="date" required value={dates.end} onChange={e=>setDates({...dates,end:e.target.value})}/><button className="secondary" disabled={busy}>Apply</button></form>}</div>{error&&<div role="alert" className="error">{error}</div>}{notice&&<div role="status" className="success">{notice}</div>}
 {page==='Overview'&&(data?<Overview {...{data,user,money,act,busy,range}}/>:<div className="panel loading">Loading performance…</div>)}
 {page==='Team'&&data&&<><div className="panel"><PanelHead title="Team scorecard" note="Based on source account assignments"/><div className="table-wrap" tabIndex={0}><table><thead><tr><th>Team member</th><th>Leads</th><th>Close rate</th><th>Median response</th><th>Jobs</th><th>Service revenue</th><th>Overdue</th></tr></thead><tbody>{data.team.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{count(p.leads)}</td><td>{pct(p.closeRate)}</td><td>{fixed(p.responseMinutes)} min</td><td>{count(p.jobs)}</td><td>{money(p.revenueCents)}</td><td>{count(p.overdue)}</td></tr>)}</tbody></table></div></div><p className="footnote">Unassigned: {count(data.unassigned.leads)} leads · {count(data.unassigned.jobs)} jobs. Close rate uses won ÷ (won + lost). Response times include supplied first-contact timestamps only.</p></>}
 {page==='Connections'&&<Connections {...{act,busy,revision,range}}/>}{page==='People'&&<People {...{act,busy,revision,user}}/>}{page==='Activity'&&<Activity revision={revision}/>}
 <footer><span><b>BAYLINE</b> Growth workspace</span><span>All amounts in {user.currency} · Missing data shown as —</span></footer></div></main></div>;
}
function PanelHead({title,note,children}){return <div className="panel-head"><div><h2>{title}</h2>{note&&<p>{note}</p>}</div>{children}</div>;}
function Stat({label,value,note,accent}){return <article className={'stat '+(accent?'stat-accent':'')}><div className="stat-label">{label}<span aria-hidden="true">↗</span></div><strong>{value}</strong><small>{note}</small></article>;}
function Overview({data:d,user,money,act,busy,range}){
 const team=user.role==='team';return <>
 <div className="summary-line"><span className="status-dot"/>{team?'Your assigned leads and completed jobs':`${d.sources.length} of ${user.role==='owner'?4:3} sources available for this exact window`}<span>Reporting by {d.timezone} business dates</span></div>
 <section aria-label="Key performance indicators" className="stats">{!team?<Stat accent label="SERVICE REVENUE" value={money(d.ops.revenueCents)} note={d.target?`${pct(d.progress)} of ${money(Number(d.target.revenue_cents))} period target`:'Completed jobs, after refunds'}/>:<Stat accent label="COMPLETED JOBS" value={count(d.ops.jobs)} note="Your assigned completed jobs"/>}<Stat label="LEAD VOLUME" value={count(d.ops.leads)} note="Created in the selected period"/><Stat label="CLOSE RATE" value={pct(d.ops.closeRate)} note={`${count(d.ops.won)} won · ${count(d.ops.lost)} lost`}/><Stat label="SPEED TO LEAD" value={d.ops.responseMinutes==null?'—':fixed(d.ops.responseMinutes)+' min'} note={`${pct(d.ops.responseCoverage)} first-contact coverage · median`}/></section>
 <div className="two-col"><section className="panel revenue-panel"><PanelHead title={team?'Your service mix':'Service revenue'} note={team?'Completed jobs in this reporting period':'TintWiz · completed jobs less refunds'}>{!team&&<span className="pill">{d.currency}</span>}</PanelHead>{!team&&<RevenueChart data={d.trend} money={money} start={d.start} end={d.end}/>}<div className="service-list">{d.services?d.services.map((s,i)=><div className="service" key={s.name}><span className={'service-dot tone-'+i}/><div><b>{s.name}</b><small>{count(s.jobs)} jobs</small></div>{!team&&<strong>{money(s.revenueCents)}</strong>}</div>):<Empty text="Import a complete TintWiz snapshot to see service performance."/>}</div></section><section className="panel attention"><PanelHead title="Needs attention" note="Alerts for your selected period"/><div className="alerts">{d.alerts.length?d.alerts.map(a=><div className={'alert '+a.tone} key={a.id}><span aria-hidden="true">!</span><p>{a.text}</p></div>):<div className="clear-state"><span>✓</span><h3>No active alerts</h3><p>Your available measures are within their configured targets.</p></div>}</div><div className="attention-bottom"><span>Follow-up coverage</span><b>{pct(d.ops.followupCoverage)}</b><small>Open leads with a supplied next follow-up</small></div></section></div>
 {!team&&<div className="two-col"><section className="panel"><PanelHead title="Advertising performance" note="Hyros · last-click attribution · configured campaigns"/><div className="mini-stats"><div><span>Ad spend</span><b>{money(d.ads?.spendCents)}</b></div><div><span>Return on spend</span><b>{d.ads?.roas==null?'—':fixed(d.ads.roas)+'×'}</b></div><div><span>Cost per lead</span><b>{money(d.ads?.cplCents)}</b></div></div>{d.ads?<div className="table-wrap" tabIndex={0}><table><thead><tr><th>Campaign</th><th>Spend</th><th>Attributed revenue</th></tr></thead><tbody>{d.ads.campaigns.map(c=><tr key={c.id}><td><b>{c.campaign}</b><small>{c.channel}</small></td><td>{money(c.spendCents)}</td><td>{money(c.revenueCents)}</td></tr>)}</tbody></table></div>:<Empty text="No accepted advertising report for this window."/>}<p className="panel-note">Attributed revenue is a marketing measure. It is separate from service revenue and accounting income.</p></section><section className="panel"><PanelHead title="Shop capacity" note="Completed-job bay minutes ÷ supplied available minutes"/><div className="capacity"><strong>{pct(d.bays?.utilization)}</strong><span>recorded bay utilization</span></div><div className="mini-stats"><div><span>Completed jobs</span><b>{count(d.ops.jobs)}</b></div><div><span>Used hours</span><b>{d.bays?fixed(d.bays.bookedMinutes/60):'—'}</b></div><div><span>Available hours</span><b>{d.bays?fixed(d.bays.availableMinutes/60):'—'}</b></div></div><p className="panel-note">Requires explicit bay capacity for every recorded job’s bay and day. Missing coverage is not treated as spare capacity.</p></section></div>}
 {user.role==='owner'&&<section className="panel finance"><PanelHead title="Financial perspective" note={`QuickBooks · ${d.finance?.basis||'accounting'} basis · owner access`}/><div className="mini-stats"><div><span>Accounting income</span><b>{money(d.finance?.incomeCents)}</b></div><div><span>Cost of goods</span><b>{money(d.finance?.cogsCents)}</b></div><div><span>Operating expenses</span><b>{money(d.finance?.expensesCents)}</b></div><div><span>Net income</span><b>{money(d.finance?.netCents)}</b></div><div><span>Net margin</span><b>{pct(d.finance?.netMargin)}</b></div></div><p className="panel-note">Net income includes other income and expenses reported by QuickBooks. These totals are never added to operational or attributed revenue.</p></section>}
 <section className="panel"><PanelHead title="Pipeline stages" note="Selected creation cohort · current observed status"/><div className="table-wrap" tabIndex={0}><table><thead><tr><th>Stage</th><th>Total</th><th>Open</th><th>Won</th><th>Lost</th><th>Abandoned</th></tr></thead><tbody>{d.pipeline?.map(p=><tr key={p.stage}><td>{p.stage}</td><td>{p.total}</td><td>{p.open}</td><td>{p.won}</td><td>{p.lost}</td><td>{p.abandoned}</td></tr>)}</tbody></table>{!d.pipeline?.length&&<Empty text={d.pipeline===null?"No lead snapshot for this window.":"No leads in this cohort."}/>}</div></section>
 <section className="panel followups"><PanelHead title="Open lead follow-ups" note="Selected creation cohort · up to 100 open leads"/><div className="table-wrap" tabIndex={0}><table><thead><tr><th>Lead reference</th><th>Pipeline stage</th><th>First contact</th><th>Next follow-up</th></tr></thead><tbody>{d.followups.map(f=><tr key={f.id}><td>{f.id}</td><td>{f.stage}</td><td>{date(f.firstContactAt)}</td><td>{date(f.nextFollowupAt)}</td></tr>)}</tbody></table>{!d.followups.length&&<Empty text={d.ops.leads==null?'No accepted lead snapshot for this window.':'No open leads in this cohort.'}/>}</div></section>
 {user.role==='owner'&&<details className="panel target-form"><summary>Configure targets for this reporting window</summary><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));act(()=>api('/targets','PUT',{...range,revenueCents:Math.round(Number(f.revenue)*100),responseMinutes:Number(f.response),closePercent:Number(f.close),minimumRoas:Number(f.roas)}),'Period targets saved.');}}><FormField label={`Service revenue target (${d.currency})`} name="revenue" type="number" min="0.01" max="10000000000" step="0.01" required defaultValue={d.target?Number(d.target.revenue_cents)/100:100000}/><FormField label="Median response target (min)" name="response" type="number" min="1" max="1440" required defaultValue={d.target?.response_minutes||15}/><FormField label="Close rate target (%)" name="close" type="number" min="1" max="100" required defaultValue={d.target?.close_percent||40}/><FormField label="Minimum ad ROAS" name="roas" type="number" min="0" max="100" step="0.01" required defaultValue={d.target?.minimum_roas||3}/><button className="primary" disabled={busy}>Save targets</button></form></details>}
 {!team&&<section className="sources" aria-label="Source freshness">{d.sources.map(s=><div key={s.provider}><b>{brands[s.provider]}</b><small>Observed {date(s.observedAt)}</small><small>Accepted {date(s.acceptedAt)}</small></div>)}</section>}
 </>;
}
function Empty({text}){return <p className="empty">{text}</p>;}
function RevenueChart({data,money,start,end}){
 if(data===null)return <Empty text="A complete snapshot is needed before revenue can be plotted."/>;
 if(!data.length)return <Empty text="The accepted report contains no completed jobs."/>;
 const amounts=new Map(data.map(x=>[x.day,x.revenueCents]));data=Array.from({length:Math.round((Date.parse(end)-Date.parse(start))/86400000)+1},(_,i)=>{const day=new Date(Date.parse(start)+i*86400000).toISOString().slice(0,10);return {day,revenueCents:amounts.get(day)||0};});
 const max=Math.max(...data.map(x=>x.revenueCents),1),n=data.length,points=data.map((x,i)=>`${55+i*(620/Math.max(n-1,1))},${190-x.revenueCents/max*145}`).join(' ');
 return <div className="chart"><svg viewBox="0 0 730 245" role="img" aria-label="Daily completed-job revenue"><title>Daily completed-job revenue</title>{[0,.5,1].map(x=><g key={x}><line x1="55" x2="700" y1={190-x*145} y2={190-x*145} stroke="#e7e9e3" strokeDasharray="4 4"/><text x="4" y={194-x*145} fill="#647573" fontSize="10">{money(max*x)}</text></g>)}<polygon points={`55,190 ${points} ${55+(n-1)*(620/Math.max(n-1,1))},190`} fill="#e6f1ed"/><polyline points={points} fill="none" stroke="#28715f" strokeWidth="3"/>{data.map((d,i)=><circle key={d.day} cx={55+i*(620/Math.max(n-1,1))} cy={190-d.revenueCents/max*145} r="4" fill="#28715f"><title>{d.day}: {money(d.revenueCents)}</title></circle>)}<text x="55" y="225" fill="#647573" fontSize="11">{data[0].day}</text><text x="675" y="225" textAnchor="end" fill="#647573" fontSize="11">{data.at(-1).day}</text></svg></div>;
}
function Connections({act,busy,revision,range}){
 const [state,setState]=useState(null),[batches,setBatches]=useState([]),[jobs,setJobs]=useState([]),[review,setReview]=useState(null),[err,setErr]=useState('');
 useEffect(()=>{let active=true;Promise.all([api('/connections'),api('/batches'),api('/syncs')]).then(([s,b,j])=>{if(active){setState(s);setBatches(b);setJobs(j);}}).catch(e=>{if(active)setErr(e.message);});return()=>{active=false;};},[revision]);
 return <>{err&&<p role="alert" className="error">{err}</p>}<div className="connection-grid">{Object.entries(brands).map(([key,name])=><section className="panel connection" key={key}><div className="connection-icon">{name.slice(0,2)}</div><span className={'badge '+(state?.[key].configured?'good':'')}>{state?.[key].configured?'Configured':'Setup required'}</span><h2>{name}</h2><p>{({ghl:'Lead cohort, status and assigned team.',tintwiz:'Completed jobs, services and bay capacity.',qbo:'Accounting income, expenses and margin.',hyros:'Campaign spend and attributed results.'})[key]}</p>{key!=='tintwiz'&&<button className="secondary" disabled={busy||!range||!state?.[key].configured} onClick={()=>act(()=>api('/syncs','POST',{provider:key,...range}),'Read queued. Run the worker, then refresh to review the result.')}>Read selected period ↗</button>}{key==='qbo'&&<><button disabled={busy} className="text-button" onClick={()=>act(async()=>{const r=await api('/oauth/qbo/start','POST',{});window.location.assign(r.url);})}>Connect with QuickBooks</button>{state?.qbo.configured&&<button disabled={busy} className="text-button" onClick={()=>act(()=>api('/oauth/qbo','DELETE'),'Local connection removed. Revoke app access in Intuit if required.')}>Disconnect locally</button>}</>}{key==='tintwiz'&&<small>Signed Zapier / export bridge → owner review</small>}</section>)}</div><section className="panel"><PanelHead title="Import a complete snapshot" note="JSON · 2 MB maximum · validate, review, then accept"/><p className="panel-note">Each import replaces one source for its exact date window. Include the complete reporting set, including explicit zero records when there was no activity. Use the repository’s contract and mapping guide.</p><label className="upload">Choose snapshot file<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const f=e.target.files[0];e.target.value='';if(!f)return;act(async()=>{if(f.size>2*1024*1024)throw new Error('Snapshot exceeds 2 MB');let p;try{p=JSON.parse(await f.text());}catch{throw new Error('Choose valid JSON');}const r=await api('/batches','POST',p);setReview(await api('/batches/'+r.id));},'Snapshot validated. Review its contents before accepting.');}}/></label></section>
 {review&&<section className="panel review"><PanelHead title={`Review ${brands[review.provider]} snapshot`} note={`${review.start_day} through ${review.end_day} · ${review.payload.records.length} records · ${review.status}`}/><p className="panel-note">Observed {date(review.payload.observedAt)} · {review.payload.currency} · {review.payload.timezone}. Acceptance replaces the existing source snapshot for this window. Reviews expire after 30 minutes.</p><details><summary>Inspect complete normalized data</summary><pre>{JSON.stringify(review.payload,null,2)}</pre></details><div className="actions"><button className="primary" disabled={busy||review.status!=='review'} onClick={()=>act(async()=>{await api('/batches/'+review.id+'/apply','POST',{});setReview(null);},'Snapshot accepted. Dashboard updated.')}>Accept snapshot</button><button disabled={busy||review.status!=='review'} className="secondary" onClick={()=>act(async()=>{await api('/batches/'+review.id+'/reject','POST',{});setReview(null);},'Review rejected.')}>Reject</button><button className="text-button" onClick={()=>setReview(null)}>Close review</button></div></section>}
 <section className="panel"><PanelHead title="Snapshot history" note="Latest 100 imports"><button className="secondary" disabled={busy} onClick={()=>act(async()=>{},'Refreshed.')}>Refresh</button></PanelHead><div className="table-wrap" tabIndex={0}><table><thead><tr><th>Source</th><th>Window</th><th>Records</th><th>Status</th><th>Review</th></tr></thead><tbody>{batches.map(b=><tr key={b.id}><td>{brands[b.provider]}</td><td>{b.start_day} → {b.end_day}</td><td>{b.records}</td><td><span className={'badge '+(b.status==='applied'?'good':'')}>{b.status}</span></td><td><button className="text-button" onClick={()=>act(async()=>setReview(await api('/batches/'+b.id)))}>Inspect</button></td></tr>)}</tbody></table>{!batches.length&&<Empty text="No imports yet. Upload a snapshot or configure a connection."/>}</div></section><section className="panel"><PanelHead title="Provider reads" note="Reads prepare a review; they never publish data automatically"/>{jobs.map(j=><div className="job-row" key={j.id}><b>{brands[j.provider]}</b><span>{j.start_day} → {j.end_day}</span><span className="badge">{j.status}</span><p>{j.message||'Waiting for the worker'}</p></div>)}{!jobs.length&&<Empty text="No provider reads queued."/>}</section></>;
}
function People({act,busy,revision,user}){
 const [people,setPeople]=useState([]),[edit,setEdit]=useState(null),[err,setErr]=useState('');
 useEffect(()=>{api('/users').then(setPeople).catch(e=>setErr(e.message));},[revision]);
 return <>{err&&<p role="alert" className="error">{err}</p>}<section className="panel"><PanelHead title="Workspace members" note="Changing a member signs out their active sessions"/><div className="table-wrap" tabIndex={0}><table><thead><tr><th>Name</th><th>Role</th><th>GHL ID</th><th>TintWiz ID</th><th>Status</th><th>Action</th></tr></thead><tbody>{people.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.email}</small></td><td>{p.role}</td><td>{p.ghl_key||'Unmapped'}</td><td>{p.tw_key||'Unmapped'}</td><td>{p.active?'Active':'Disabled'}</td><td><button className="text-button" onClick={()=>setEdit(p)}>Edit</button></td></tr>)}</tbody></table></div></section><section className="panel"><PanelHead title={edit?'Edit member':'Add a member'} note="Owner: all data · Manager: operations & ads · Team: own assigned work"/><form key={edit?.id||'new'} className="form-grid" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));act(async()=>{await api(edit?'/users/'+edit.id:'/users',edit?'PUT':'POST',{...f,active:f.active==='true'});setEdit(null);},'Member saved.');}}><FormField label="Name" name="name" required defaultValue={edit?.name}/><FormField label="Email" type="email" name="email" required defaultValue={edit?.email}/><label>Role<select name="role" defaultValue={edit?.role||'team'}><option>team</option><option>manager</option><option>owner</option></select></label>{!edit&&<FormField label="Initial password (12+ characters)" type="password" name="password" minLength="12" maxLength="128" autoComplete="new-password" required/>}<FormField label="GoHighLevel staff ID" name="ghl_key" defaultValue={edit?.ghl_key||''}/><FormField label="TintWiz staff ID" name="tw_key" defaultValue={edit?.tw_key||''}/>{edit&&<label>Status<select name="active" defaultValue={String(edit.active)}><option value="true">Active</option><option value="false">Disabled</option></select></label>}<div className="actions"><button className="primary" disabled={busy}>Save member</button>{edit&&<button type="button" className="secondary" onClick={()=>setEdit(null)}>Cancel</button>}</div></form></section></>;
}
function Activity({revision}){const [rows,setRows]=useState([]),[err,setErr]=useState('');useEffect(()=>{api('/activity').then(setRows).catch(e=>setErr(e.message));},[revision]);return <section className="panel"><PanelHead title="Workspace activity" note="Latest 300 entries · append-only"/>{err&&<p role="alert" className="error">{err}</p>}<div className="table-wrap" tabIndex={0}><table><thead><tr><th>When</th><th>Who</th><th>Action</th><th>Reference</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{date(r.created_at)}</td><td>{r.name||'Signed bridge'}</td><td>{r.action.replaceAll('_',' ')}</td><td className="mono">{r.reference}</td></tr>)}</tbody></table></div></section>;}
createRoot(document.getElementById('root')).render(<App/>);
