const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');
(async()=>{
 const {database,migrate}=await import('../backend/db.js'),{PGlite}=await import('@electric-sql/pglite'),{createApp}=await import('../backend/app.js'),{config}=await import('../backend/config.js'),{seed}=await import('./demo.js');
 const db=process.env.TEST_DATABASE_URL?await database(process.env.TEST_DATABASE_URL):new PGlite();await db.exec('DROP SCHEMA public CASCADE; CREATE SCHEMA public;');await migrate(db);const settings=config({APP_ORIGIN:'http://127.0.0.1:3098',BUSINESS_TIMEZONE:'UTC'}),password='Fictional-demo-password-2026';const seeded=await seed(db,settings,password);const server=createApp({db,config:settings}).listen(3098,'127.0.0.1');
 let browser,context,page;const errors=[];try{
  browser=await chromium.launch({headless:true});context=await browser.newContext({viewport:{width:1440,height:1000}});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error'&&!msg.text().includes('401'))errors.push(msg.text());});await fs.mkdir('evidence',{recursive:true});
  const login=async role=>{await page.getByLabel('Email address',{exact:true}).fill(role+'@example.test');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in →'}).click();await page.getByRole('heading',{name:'Performance overview'}).waitFor();await page.getByRole('heading',{name:'Open lead follow-ups'}).waitFor();};
  await page.goto(settings.origin);await page.screenshot({path:'evidence/login-desktop.png',fullPage:true});await login('owner');await page.getByRole('heading',{name:'Financial perspective'}).waitFor();await page.screenshot({path:'evidence/dashboard-desktop.png',fullPage:true});
  await page.getByText('Configure targets for this reporting window',{exact:true}).click();await page.getByLabel('Service revenue target (USD)').fill('125000');await page.getByRole('button',{name:'Save targets',exact:true}).click();await page.getByRole('status').filter({hasText:'Period targets saved'}).waitFor();
  await page.getByRole('button',{name:'Team',exact:true}).click();await page.getByRole('heading',{name:'Team scorecard'}).waitFor();assert.equal(await page.getByRole('cell',{name:'Sam Rivera',exact:true}).count(),1);
  await page.getByRole('button',{name:'Connections',exact:true}).click();await page.getByRole('heading',{name:'Import a complete snapshot'}).waitFor();const payload={...seeded.snapshots[0],observedAt:new Date().toISOString()};await page.getByLabel('Choose snapshot file').setInputFiles({name:'ghl.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))});await page.getByRole('heading',{name:'Review GoHighLevel snapshot'}).waitFor();await page.getByText('Inspect complete normalized data').click();await page.screenshot({path:'evidence/import-review.png',fullPage:true});await page.getByRole('button',{name:'Accept snapshot',exact:true}).click();await page.getByRole('status').filter({hasText:'Snapshot accepted'}).waitFor();
  await page.getByRole('button',{name:'People',exact:true}).click();await page.getByRole('heading',{name:'Add a member'}).waitFor();await page.getByLabel('Name',{exact:true}).fill('Taylor Park');await page.getByLabel('Email',{exact:true}).fill('taylor@example.test');await page.getByLabel('Initial password (12+ characters)').fill(password);await page.getByRole('button',{name:'Save member',exact:true}).click();await page.getByRole('cell',{name:'Taylor Park'}).waitFor();
  await page.getByRole('button',{name:'Activity',exact:true}).click();await page.getByRole('cell',{name:'user created',exact:true}).waitFor();await page.getByRole('button',{name:'Overview',exact:true}).click();await page.getByRole('heading',{name:'Financial perspective'}).waitFor();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'evidence/dashboard-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile viewport overflows');
  await page.getByRole('button',{name:'Sign out ↗',exact:true}).click();await login('manager');assert.equal(await page.getByRole('heading',{name:'Financial perspective'}).count(),0);assert.equal(await page.getByRole('button',{name:'Connections',exact:true}).count(),0);await page.getByRole('button',{name:'Sign out ↗',exact:true}).click();await login('team');assert.equal(await page.getByRole('button',{name:'Team',exact:true}).count(),0);assert.equal(await page.getByRole('heading',{name:'Advertising performance'}).count(),0);assert.equal(await page.getByRole('heading',{name:'Financial perspective'}).count(),0);await page.screenshot({path:'evidence/team-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  const result=await page.evaluate(async()=>{const me=await(await fetch('/api/me')).json();const now=new Date().toISOString().slice(0,10);return (await fetch('/api/dashboard?'+new URLSearchParams({start:now.slice(0,8)+'01',end:now}))).json();});assert.equal(result.ops.revenueCents,undefined);assert.equal(result.ads,undefined);assert.equal(result.team,undefined);assert.equal(errors.length,0,errors.join('\n'));console.log('Browser passed: owner targets, import review/accept, users, activity, manager and team isolation, desktop/mobile.');
 }catch(e){if(page)await page.screenshot({path:'evidence/failure.png',fullPage:true});throw e;}finally{await context?.close();await browser?.close();await new Promise(r=>server.close(r));await db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
